spring:
  thymeleaf:
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_in_action?characterEncoding=utf-8&useSSL=false
    username: root
    password: zwz520
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: zwz520
mybatis:
  type-aliases-package: com.ximo.seckillinaction.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:mapper/*.xml
